var Router = Ember.Router.extend({
  // use pushState instead of hashchange on URLs
  location: 'history'
});

Router.map(function() {
  this.resource('todos', { path: '/' }, function() {
    // this.route('index', { path: '/' });  // this route is autogenerated
    this.route('active');
    this.route('completed');
  });
});

export default Router;